### ISSUE TITLE
official ast parser

### ISSUE THREAD

**Issue by lepture** [e7h4n/grunt-cmd-combo#2]
use our ast parser, it's stable now (0.2.0), and 100% coverage test.
- https://github.com/spmjs/cmd-util
- https://github.com/spmjs/cmd-util/blob/master/docs/ast.md

**Comment by lepture** [comment]
@AlanGuo what do you mean by this? If it is not related to my issue please open another one.

**Comment by e7h4n** [comment]
@lepture thanks, I'll try it later.
