### ISSUE TITLE
关于 seajs plugin-text

### ISSUE THREAD

**Issue by AlanGuo** [e7h4n/grunt-cmd-combo#3]
我在项目中使用了seajs 的plugin-text，在运行grunt combo的时候，没办法处理这些 require语句(require("text!xxx.html")，我只能将他们改写成 $.get()，我就是想看能不能把这个加载html的功能也做进来就完美啦~
总的来说，这个工具相当不错！

**Comment by lifesinger** [comment]
这个不要着急，接下来 seajs 支持的插件，都会有对应的 grunt-task 来提供构建支持
这个月内会出来

2013/3/6 AlanGuo notifications@github.com

> 我在项目中使用了seajs 的plugin-text，在运行grunt combo的时候，没办法处理这些
> require语句(require("text!xxx.html")，我只能将他们改写成
> $.get()，我就是想看能不能把这个加载html的功能也做进来就完美啦~
> 总的来说，这个工具相当不错！
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/perfectworks/grunt-cmd-combo/issues/3
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by e7h4n** [comment]
@AlanGuo grunt-cmd-combo 只支持 SeaJS 的一个特性子集，并且只做一件事：combo。更复杂的功能请期待 SeaJS 的构建工具。

@lifesinger 期待牛逼闪闪的 SeaJS 构建 task
