### ISSUE TITLE
require为什么只支持相对路径？

### ISSUE THREAD

**Issue by twinstony** [e7h4n/grunt-cmd-combo#6]
原有的代码都是通过别名处理依赖的，如果想用这个必须要修改源码么？

**Comment by e7h4n** [comment]
这个是 SeaJS 支持特性的一个最精简的子集，不支持 alias。

alias 会增加代码的复杂度，而且也不是所有人都会用到这个特性。  

Regards,
Ethan Zhang

## 

晓来雨过 遗踪何在 一池萍碎 春色三分 两分尘土 一分流水
perfectworks@gmail.com

**Comment by twinstony** [comment]
那就是说只能支持没用过别名的seajs项目了。。。。。。这太遗憾了。
虽然维持最精简的loader.js听起来挺好，但真的是给使用者带来了麻烦啊！是不是可以考虑支持下？

**Comment by e7h4n** [comment]
请期待 spm 2.0 正式发布，或者 fork 代码自己动手丰衣足食啦

Regards,
Ethan Zhang

## 

晓来雨过 遗踪何在 一池萍碎 春色三分 两分尘土 一分流水
perfectworks@gmail.com

**Comment by twinstony** [comment]
问下，现在构建怎么这么多？都是些什么关系？比如combo，spm，还有grunt-spm

**Comment by e7h4n** [comment]
spm 是 SeaJS package manager，官方的构建工具。
grunt 是一个 javascript 任务系统，grunt-spm 是在 grunt 中调用 spm 的任务。

至于 grunt-cmd-combo，是 seajs 的一个第三方构建任务。  

Regards,
Ethan Zhang

## 

晓来雨过 遗踪何在 一池萍碎 春色三分 两分尘土 一分流水
perfectworks@gmail.com

**Comment by twinstony** [comment]
谢谢解答，也就是说，这三种方法理论上（符合条件）都能独立的满足构建部署的工作，而不用交叉使用，不知道这样理解对不对？

**Comment by e7h4n** [comment]
是的，只不过不是相互独立关系，grunt-spm 会调用 spm。而 grunt-cmd-combo 是完全独立的一个项目，不依赖与 spm

Regards,
Ethan Zhang

## 

晓来雨过 遗踪何在 一池萍碎 春色三分 两分尘土 一分流水
perfectworks@gmail.com

**Comment by hellolibo** [comment]
看了文档，我理解是把所有依赖都打包，不管是不是通用的模块，还是当前业务的模块。

**Comment by e7h4n** [comment]
是的

Regards,
Ethan Zhang

## 

晓来雨过 遗踪何在 一池萍碎 春色三分 两分尘土 一分流水
perfectworks@gmail.com
